name = "portfolio"
compatibility_date = "2025-05-01"
compatibility_flags = ["nodejs_compat"]

[vars]
PUBLIC_API_URL = "https://api.shashwatdixit.com"
PUBLIC_POSTHOG_KEY = ""
PUBLIC_POSTHOG_HOST = "https://us.i.posthog.com"

[assets]
directory = "./dist/client"
